# Generated by Django 5.0.14 on 2026-01-02 16:31

import characters.defaults
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('code', models.CharField(help_text='Stable ID such as CHAR-001', max_length=32, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]+$', 'Use letters, numbers, dashes, or underscores.')])),
                ('name', models.CharField(blank=True, max_length=120)),
                ('player', models.CharField(blank=True, max_length=120)),
                ('profession', models.CharField(blank=True, max_length=120)),
                ('data', models.JSONField(blank=True, default=characters.defaults.default_character_data)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
